binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions:
  OverloadedStrings: true
  TypeOperators: true
  TypeFamilies: true
  DeriveGeneric: true
  DataKinds: true
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: string-conversions 0.3.0.3

  Hackage: servant 0.2.1'
ghc-args: []
excluded-modules: []
